### ISSUE TITLE
Inconsistências e melhorias no fluxo de criação e configuração da coleção

### ISSUE THREAD

**Issue by juliannyasilva** [medialab-ufg/tainacan#274]
Cenário do fluxo: https://s.nimbus.everhelper.me/share/1215496/hp0qeuiddyc7f12mc9p5
### 1 Geral
- [ ] Já que no fluxo possui os botões "prosseguir", "salvar e continuar", "salvar" para percorrer as abas de configuração. Logo, bloquear navegar entra as abas clicando no nome da aba. Deixando o percurso de ir e voltar nas abas no botão "Voltar" e "Prosseguir" na parte inferior dos formulários. Acabando assim com bugs simples e melhorias importantes. Logo, remover os links no titulo das abas.
- [ ] Remover o botão "Deletar" pois o mesmo alem de está fora do estilo padrão de botões, a mesma funcionalidade já é executada na parte inferior do formulário no botão "Voltar para coleção" que será renomeado para "Cancelar".
- [ ] **Opção 1**: Manter o botão "Finalizar" na parte superior, mas ao clicar no mesmo, emitir ao usuário a mensagem "Esta coleção será finalizada com as configurações padrão do repositório, sem aplicação das suas primeiras personalizações (mas poderão ser feitas posteriormente). Deseja finalizar?"
**Opção 2**: Remover o botão "Finalizar".
![image](https://user-images.githubusercontent.com/11639242/32287660-aedc0f0e-bf18-11e7-899b-59c7efe17bcd.png)

### 2 Coleção
- [ ] Desativar no menu da coleção as funcionalidades como compartilhar, configurações da coleção, alteração de capa e miniatura, habilitar somente quando a coleção já estiver finalizada. Por que ao clicar nestas funcionalidades (exceto alteração de capa), o sistema redireciona o usuário para interface de uma coleção já criada, desviado o fluxo de criação de coleção.
![image](https://user-images.githubusercontent.com/11639242/32287196-23c3bcb0-bf17-11e7-913f-2813b3cb528d.png)

### 3 Configurações
- [ ] Este item tem total relação com a issue #188 , logo sera atendido quando a issue for fechada.
- [ ] Na aba de configuração renomear o botão "Voltar para a coleção" para "Cancelar" e implementar no mesmo o descarte da coleção em criação. (Não persistindo a coleção no sistema).
- [ ] Na aba de configuração renomear o botão "Salvar" para "Salvar e Continuar" e implementar no mesmo o salvamento das configurações feitas da coleção e redirecionar para a aba "Metadados".
- [ ] Retirar o rodape da pagina para evitar que ao clicar em tais links seja redirecionado para ourta interface e interrompa o fluxo de criação de coleção. Ou, bloquear o acesso ao links emitindo uma mensagem que o usuário será redirecionado para outra interface e perderá a coleção em criação (neste momento não persistir a coleção se o usuário escolher 'ir e descartar').
![image](https://user-images.githubusercontent.com/11639242/32287608-8c990690-bf18-11e7-8422-4ad784d5de4c.png)

### 4 Categorias
- [ ] Este item tem total relação com a issue #266 , logo sera atendido quando a issue for fechada.
- [ ] Informar categorias nesta interface e não clicar no botão "Salvar e prosseguir" o sistema não persiste as categorias.
- [ ] Renomear o botão 'voltar para coleção' para "Voltar". E alterar o redirecionamento do botão "Voltar" para voltar a aba de configuração. 
- [ ] Se deixar o campo onde é apresentado "assunto..." e tentar avançar o sistema emite mensagem informando que o campo deve ser preenchido. Mas não importa o nome colocado neste campo o sistema sempre cria um metadado com o nome "Assunto" por padrão na coleção. Pensando nisso retirar este campo, ou mudar a regra em cima dele. Até porque na tela de metadados é possível excluir o metadado "Assunto".
![image](https://user-images.githubusercontent.com/11639242/32293567-b049f72c-bf2a-11e7-909b-ec5809055737.png)

### 5 Metadados
- [ ] Este item tem total relação com a issue #204 , logo sera atendido quando a issue for corrigida.
- [ ] Como no item assim a exclusão de metadados do usuário e a criação de novos metadados desocultam os metadados ocultados.
- [ ] Ao adicionar um metadado a uma aba, e posteriormente edita-lo alterando sua aba de destino, o sistema não atualiza a pagina e move o metadado para a aba escolhida. Só ao realizar uma interação que requer atualizar (ex. criar metadado) que o mesmo é movido. Ou seja, mover o metadado para a aba de acordo que for alterado. 
- [ ] Revisar os tipos de metadados do sistema pois os metadados padrões possuis tipos que não podem ser adicionados via o botão de adicionar metadados como por exemplo: Licença (radio), Tipo (arquivo), no qual radio e arquivo não são metadados disponíveis para adição. Mas possui metadados com esses tipos.
- [ ] Criar o botão "Voltar" na parte inferior do formulário redirecionando para a aba de categorias.

### 6 Layout
- [ ] Renomear as formas de ordenação para "Crescente" e "Decrescente". 
- [ ] Atualizar a forma de ordenação por metadados de dados de acordo com os metadados personalizados na aba metadados e filtros. Como podemos ver na imagem tais metadados gerais foram ocultados e mesmo assim continuam sendo apresentados como forma de ordenação. E os metadados que eu criei novos não. Deveria apresentar os metadados de dados criados pelo usuário. 
![image](https://user-images.githubusercontent.com/11639242/32294302-dcbd12f6-bf2c-11e7-98ec-ae5ee469d4ab.png)
- [x] Alterar o redirecionamento do botão "Voltar" para voltar a aba de metadados. 
- [ ] Renomear o botão a baixo de "Salvar" para "Finalizar".
![image](https://user-images.githubusercontent.com/11639242/32294344-0900224a-bf2d-11e7-9263-6baec4c6daf3.png)

**Comment by juliannyasilva** [comment]
@leogermani e @marcelf  eu elicitei algumas correções e melhorias que deixaria o processo de criação bem mais claro para o usuário final (no meu ponto de vista), não sabendo muito a forma que trabalha a criação das coleção internamente, bem como sua forma de configuração. Acha interessante aplicar correções como esta nesta interface, e em outras como #257 ? Acordar com os interessados(gestores e usuários) essas questões, pois se vamos manter este formato por longo tempo, buscar deixar mais bonitinho e fáceis algumas interfaces.
